#!/bin/bash
set -e

main() {
  DAY=$1
  DFLAGS_ARR=()
  CLEAN=
  INPUT=

  shift
  parse_args $@

  # Find dependencies of the code to libs
  DEPS_ARR=()
  for dep in IntCodeProgram Point2D
  do
    if grep -q "import $dep;" $DAY.d
    then
      DEPS_ARR+=("$dep.a")
    fi
  done

  if [ -n "$CLEAN" ]
  then
    make -s clean
  fi

  export DEPS="${DEPS_ARR[@]}"
  export DFLAGS="${DFLAGS_ARR[@]}"
  make -s $DAY.run
  time ./$DAY.run <input/$DAY.in$INPUT
}

parse_args() {
  local opt
  while getopts ":coduh2345" opt; do
    case $opt in
      c) CLEAN=1;;
      o) DFLAGS_ARR+=("-O" "-release" "-inline" "-boundscheck=off");;
      d) DFLAGS_ARR+=("-debug");;
      u) DFLAGS_ARR+=("-unittest");;
      2) INPUT="2";;
      3) INPUT="3";;
      4) INPUT="4";;
      5) INPUT="5";;
      h|?) help; exit 1;;
    esac
  done
}

help() {
  echo Usage: ./run program [-douh]
  echo Options:
  echo   -c              Remove old compiled files
  echo   -d              Enable debug output
  echo   -o              Optimize program
  echo   -u              Run unittests
  echo   -h              Show this help text
  echo   -2              Run with input file 2
  echo   -3              Run with input file 3
  echo   -4              Run with input file 4
  echo   -5              Run with input file 5
}

main $@
